### PR TITLE
Fix #5

### LINKED ISSUE #5: ImportError: No module named 'device'
Dear Girish,

while running the example program on windows 8.1 I get this error

```
Traceback (most recent call last):
  File "C:\Users\Elcot\Desktop\R305\python-R305-master\examples\store_finger_print.py", line 4, in <module>
    from r305 import R305
  File "C:\Python34\lib\site-packages\r305\__init__.py", line 4, in <module>
    from device import *
ImportError: No module named 'device'
```

even through I connect with R305 by using UART to USB converter

### PR DESCRIPTION
**Pull request by gabrielkrell**
In python3 we have to specify that this is a relative import: https://stackoverflow.com/a/12173406

### CODE REVIEW

**Comment by gabrielkrell** [comment]
(I tested this and it seems like it still works on Python 2.)

**Comment by gabrielkrell** [comment]
Oops, needs more work to fix other import errors that happen when this is actually run on Python 3.

**Comment by gabrielkrell** [comment]
Think it's ready now.

**Comment by girish946** [comment]
@gabrielkrell Thanks for the PR.

**Pull request merged**
